In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('train.csv')

In [7]:
df.head()

,sample_id,catalog_content,image_link,price
0,33127,"Item Name: La Victoria Green Taco Sauce Mild, ...",https://m.media-amazon.com/images/I/51mo8htwTH...,4.89
1,198967,"Item Name: Salerno Cookies, The Original Butte...",https://m.media-amazon.com/images/I/71YtriIHAA...,13.12
2,261251,"Item Name: Bear Creek Hearty Soup Bowl, Creamy...",https://m.media-amazon.com/images/I/51+PFEe-w-...,1.97
3,55858,Item Name: Judee’s Blue Cheese Powder 11.25 oz...,https://m.media-amazon.com/images/I/41mu0HAToD...,30.34
4,292686,"Item Name: kedem Sherry Cooking Wine, 12.7 Oun...",https://m.media-amazon.com/images/I/41sA037+Qv...,66.49

In [15]:
df.loc[0,'catalog_content']

'Item Name: La Victoria Green Taco Sauce Mild, 12 Ounce (Pack of 6)\nValue: 72.0\nUnit: Fl Oz\n'

In [19]:
df.sample(100)

,sample_id,catalog_content,image_link,price
40969,297722,Item Name: Rani Cumin Seeds Whole (Jeera) Spic...,https://m.media-amazon.com/images/I/91+TDKMRh0...,6.990
27560,67851,Item Name: Joffrey's Coffee - Disney Hocus Poc...,https://m.media-amazon.com/images/I/61AWGXGPJ5...,24.990
11949,222371,"Item Name: Beulah's Easter Candy Corn, 2 Pound...",https://m.media-amazon.com/images/I/81QVD-2Jwe...,20.760
28425,150026,Item Name: 505 SOUTHWESTERN Mild Green Chile S...,https://m.media-amazon.com/images/I/71gVEs3h+3...,3.320
64789,140006,"Item Name: Pringles, Potato Crisps Chips, Ched...",https://m.media-amazon.com/images/I/81xj3jW1ei...,2.590
...,...,...,...,...
12638,49546,"Item Name: KING ARTHUR MIX PANCAKE GF, 15 OZ P...",https://m.media-amazon.com/images/I/715pRUmlT+...,5.790
20441,161786,"Item Name: Sara Lee Cherry Cheesecake, 19 Ounc...",https://m.media-amazon.com/images/I/21at--nTsB...,165.010
50101,241031,Item Name: Chicken & Waffles Seasoning Topper ...,https://m.media-amazon.com/images/I/81rciG7JFj...,12.125
21802,110584,Item Name: Grinds Coffee Pouches | Tobacco Fre...,https://m.media-amazon.com/images/I/81sEd44F9C...,15.750
29142,147202,"Item Name: Horchata White Tea (Loose) (8 oz, Z...",https://m.media-amazon.com/images/I/81Wh-wPzA2...,97.460

In [21]:
new_df=df.sample(100)

In [25]:
new_df.to_csv('subset of train.csv')